apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeops-frontend
  labels:
    app: nodeops
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeops
      component: frontend
  template:
    metadata:
      labels:
        app: nodeops
        component: frontend
    spec:
      containers:
      - name: frontend
        image: nodeops:frontend-latest
        ports:
        - containerPort: 3000
        env:
        - name: NEXT_PUBLIC_API_URL
          value: "http://nodeops-backend:3001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeops-backend
  labels:
    app: nodeops
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodeops
      component: backend
  template:
    metadata:
      labels:
        app: nodeops
        component: backend
    spec:
      containers:
      - name: backend
        image: nodeops:backend-latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3001"
        - name: SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: nodeops-secrets
              key: supabase-url
        - name: SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: nodeops-secrets
              key: supabase-anon-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: nodeops-frontend
spec:
  selector:
    app: nodeops
    component: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: nodeops-backend
spec:
  selector:
    app: nodeops
    component: backend
  ports:
  - protocol: TCP
    port: 3001
    targetPort: 3001
  type: ClusterIP
